spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

    consumer:
      group-id: order-audit-group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.value.default.type: com.web.demo.dtos.OrderEvent
        spring.json.trusted.packages: "*"
        #spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        max.poll.records: 500
        session.timeout.ms: 15000
        heartbeat.interval.ms: 3000

    listener:
      ack-mode: MANUAL
      concurrency: 3

logging:
  level:
    org.springframework.kafka: INFO
